version: '3.1'

services: 

  wordpress:
    image: wordpress
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    ports: 
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin42
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin42
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    



